import pandas as pd
df = pd.DataFrame([
    {"uuid": "b2303ab7-f978-4576-b563-899f73397ed5", "postText": ["Guess who hasn't seen the Star Wars: The Force awakens trailer?"], "targetParagraphs": ["On YouTube alone, the teaser trailer for Star Wars: The Force Awakens has more than 12 million views, but you can count one person out of that number: George Lucas, the man who created the Star Wars universe.", "Page Six asked Lucas for his thoughts on the 88-second glimpse into the future of the galaxy far, far away, only to discover that he had none.", "\"I don't know anything about it,\" Lucas said. \"I haven't seen it yet.\"", "Asked why, he explained that it was \"Because it's not in the movie theater. I like going to the movies and watching the whole thing there.", "\"I plan to see it when it's released.\"", "The filmmaker sold Lucasfilm and its attending franchises to Disney in October 2012 in a deal worth more than $4 billion. At the announcement, Disney revealed that Star Wars: Episode VII was in production, based on Lucas' outline. According to Disney's announcement, Lucas would serve as a \"creative consultant\" for the franchise.", "Disney announced the cast of the next installment, which includes actors from the original trilogy, in April 2014. The first trailer hit on Black Friday. Directed by J.J. Abrams, Star Wars: The Force Awakens is slated to open Dec. 15, 2015. You can watch the teaser trailer below. For more on what it might mean, be sure to read Polygon's analysis."], "targetTitle": "George Lucas doesn't 'know anything about' the new Star Wars trailer", "targetDescription": "On YouTube alone, the teaser trailer for Star Wars: The Force Awakens has more than 12 million views, but you can count one person out of that number: George Lucas, the man who created the Star...", "targetUrl": "http://polygon.com/e/7119322", "provenance": {"source": "anonymized", "humanSpoiler": "George Lucas.", "spoilerPublisher": "SavedYouAClick"}, "spoiler": ["George Lucas"], "spoilerPositions": [[[0, 151], [0, 163]]], "tags": ["phrase"]},
    {"uuid": "09f9794e-134e-4e58-8ec2-8259ec40c136", "postText": ["Has \"Star Trek 3\" found its director?"], "targetParagraphs": ["Joe Cornish could replace J.J. Abrams as king of the \"Star Trek\" universe. That's the report from Deadline.com's Mike Fleming, who writes that Paramount \"is sweet\" on the idea of Cornish directing the franchise's next installment.", "This isn't the first time Cornish, who directed the cult hit \"Attack the Block\" and co-wrote the script for \"Ant-Man\" with Edgar Wright, has had his name attached to \"Star Trek 3.\" Back in May, Latino Review reporter Umberto \"El Mayimbe\" Gonzalez tweeted that Cornish was under consideration as a possible replacement for Abrams, who is next directing \"Star Wars: Episode VII.\"", "I guess y'all wanna know about who might be directing STAR TREK 3 if it ever goes. Heard Joe Cornish BUT also heard he's on a list of names. — elmayimbe (@elmayimbe) May 23, 2013", "I'm NOT saying Joe Cornish is the guy, but what I am saying is the he is definitely one of NUMEROUS contenders. — elmayimbe (@elmayimbe) May 23, 2013", "Other reported contenders for \"Star Trek 3\" have included Jon M. Chu and Rupert Wyatt. In an email to HuffPost Entertainment, however, Chu's representatives denied that \"G.I. Joe: Retaliation\" director was up for the job. Wyatt's involvement was never confirmed or denied, but Abrams did discuss the \"Rise of the Planet of the Apes\" director in an interview with HitFix.", "\"Whomever it is that directs the film will be someone we all know is going to keep the cast and crew in good hands,\" Abrams told Collider back in September. \"I feel very lucky to have been part of it, and it definitely feels like the right time to let someone come in and do their own thing. I certainly don’t want someone to come in and try to do what I would have done. We want to hire someone who's gonna come in and bring their own sensibility. I'm very excited to see what comes next, despite feeling jealous of whomever that person is.\"", "HuffPost Entertainment contacted Cornish's representatives for comment on the Deadline.com rumor; this post will be updated if they respond. For more on Cornish, meanwhile, head to Deadline.com.", "[via Deadline.com]"], "targetTitle": "Joe Cornish Rumored For 'Star Trek 3' Director Job", "targetDescription": "Joe Cornish could replace J.J. Abrams as king of the \"Star Trek\" universe. That's the report from Deadline.com's Mike Fleming,", "targetUrl": "http://huff.to/1aVGhr4", "provenance": {"source": "anonymized", "humanSpoiler": "This article doesn't know but the rumor is Joe Cornish", "spoilerPublisher": "HuffPoSpoilers"}, "spoiler": ["Joe Cornish could replace J.J. Abrams as king of the \"Star Trek\" universe."], "spoilerPositions": [[[0, 0], [0, 74]]], "tags": ["passage"]},
])

df

import importlib
baseline = importlib.import_module('transformer-baseline-task-2')

results = pd.DataFrame(baseline.predict([i for _, i in df.iterrows()]))

results