wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.32.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690941016.322273
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 23
      4: 3.10.11
      5: 0.15.7
      6: 4.32.0.dev0
      8:
      - 5
